services:
  postgres:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - '${POSTGRES_PORT}:5432'
    env_file:
      - .env
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_INITDB_ROOT_PASSWORD
    volumes:
      - ./data/mongodb:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - '${ME_PORT}:8081'
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=$ME_CONFIG_MONGODB_ADMINUSERNAME
      - ME_CONFIG_MONGODB_ADMINPASSWORD=$ME_CONFIG_MONGODB_ADMINPASSWORD
      - ME_CONFIG_MONGODB_SERVER=$ME_CONFIG_MONGODB_SERVER
    depends_on:
      - mongodb

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - '${REDIS_PORT}:6379'
    env_file:
      - .env
    volumes:
      - ./data/redis:/data

volumes:
  postgres_data:
  mongodb_data:
  redis_data:
